all: caesar combination mainboi

caesar : caesar.c
	gcc caesar.c -o caesar
combination : combination.c
	gcc combination.c -o combination
mainboi : mainboi.c
	gcc mainboi.c -o main

clean:
	rm caesar combination main
