all: copy list move remove

copy: copy.c
	gcc copy.c -o copy
list: list.c
	gcc list.c -o list
move: move.c
	gcc move.c -o move
remove: remove.c
	gcc remove.c -o remove

clean:
	rm copy list move remove

open: 
	nano copy.c move.c list.c remove.c

